# Generated by Django 2.2.5 on 2019-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('calorie', models.PositiveSmallIntegerField(verbose_name='Калорийность')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Без категории'), (0, 'Закуски'), (1, 'Горячие блюда'), (2, 'Десерты'), (3, 'Напитки'), (4, 'Алкогольные напитки')], null=True)),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('picture', models.ImageField(default='static/images/menu/no_img.jpg', upload_to='static/images/menu/')),
                ('allergen', models.ManyToManyField(blank=True, related_name='dish', to='app.Allergen', verbose_name='Аллергены')),
            ],
        ),
    ]
